### ISSUE TITLE
Unable to measure after connecting to GLM50C

### ISSUE THREAD

**Issue by cgommel** [philipptrenz/BOSCH-GLM-rangefinder#3]
I patched the file that it can also find the GLM50C. 
```
>>> rangefinder = GLM100C()
Searching for BOSCH GLM100C ...
BOSCH GLM50C X9225
Found BOSCH GLM100C @ 00:13:43:71:78:EF
```

but then a new error appeared on my Raspberry Pi Zero W with raspbian:
```
>>> rangefinder.measure_from_back()
Traceback (most recent call last):
  File "<string>", line 3, in send
_bluetooth.error: (9, 'Bad file descriptor')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chg/git/BOSCH-GLM-rangefinder/glm100c.py", line 103, in measure_from_back
    m = self.measure()
  File "/home/chg/git/BOSCH-GLM-rangefinder/glm100c.py", line 78, in measure
    self.socket.send(self.cmds['measure'])
  File "<string>", line 5, in send
bluetooth.btcommon.BluetoothError: (9, 'Bad file descriptor')
```
Running with sudo did not improve the situation so this is not a permission issue ;(
Any Ideas what's wrong?

**Comment by cgommel** [comment]
It can be solved by setting port to 0x0005. Will adapt this in my fork later on.

**Comment by philipptrenz** [comment]
Thanks for your work! I'd be glad if you create a pull request, so that I can merge your improvements and mention you as contributor.
